#!/usr/bin/env bash -e

help()
{
    echo 'sinister is a simple installer for shell scripts.'
    echo
    echo 'Usage: sinister [-n|--name name] [-o|--output dir] [-u|--url url]'
    echo
    echo 'name: The name of the file the script should be saved to. Mandatory if no URL is given.'
    echo
    echo 'url: The location of the script online. e.g: https://github.com/you/repo/raw/master/script'
    echo 'If no URL is given the script is read from stdin.'
    echo
    echo 'output: The output directory the script should be saved to.'
    echo 'By default this is /usr/local/bin on Unix systems, and C:\Users\you\AppData\Local\script on Windows.'
}

on_windows()
{
    uname | grep -q '[CYGWIN|MINGW|MSYS]'
}

ps_run()
{
    powershell -NoProfile -ExecutionPolicy Bypass "$1"
}

ps_getpath()
{
    ps_run "[Environment]::GetEnvironmentVariable('PATH', 'User')"
}

ps_setpath()
{
    ps_run "[Environment]::SetEnvironmentVariable('PATH', '$1', 'User')"
}

ps_pwd()
{
    ps_run "Get-Location"
}

NAME=''
URL=''

if on_windows; then
    OUTPUT='~/AppData/Local'
else
    OUTPUT='/usr/local/bin'
fi

while [ $# -gt 0 ]
do
    case "$1" in
        '-?'|-h|--help) help; exit 0 ;;
        -n|--name) NAME="$2"; shift ;;
        -o|--output) OUTPUT="$2"; shift ;;
        -u|--url) URL="$2"; shift ;;
        *) help; exit 1 ;;
    esac
    shift
done

if [ -z "$URL" ]; then
    test ! -z "$NAME"
    SCRIPT=$(< /dev/stdin) # read from standard input
else
    NAME=${URL##*/} # Grab everything after the last /
    if which curl &> /dev/null; then
        SCRIPT=$(curl -sSL "$URL")
    else # Assume wget is installed
        SCRIPT=$(wget -q -O - "$URL")
    fi
fi

# Where the magic happens
cd "$OUTPUT"
echo "$SCRIPT" > "$NAME"
chmod +x "$NAME"

# Add $OUTPUT to PATH if it's not in it
if ! which "$NAME" &> /dev/null; then
    if on_windows; then
        CURRENT_PATH=$(ps_getpath)
        CURRENT_DIRECTORY=$(ps_pwd)
        ps_setpath "$CURRENT_PATH;$CURRENT_DIRECTORY"
    else # Unix
        echo "export PATH=\$PATH:$OUTPUT" >> ~/.profile
    fi
fi
