#!/usr/bin/env bash -e

help()
{
    echo 'sinister is a simple installer for shell scripts.'
    echo
    echo 'Usage: sinister [-n|--name name] [-o|--output dir] [-u|--url url]'
    echo
    echo 'name: The name of the file the script should be saved to. Mandatory if no URL is given.'
    echo
    echo 'url: The location of the script online. e.g: https://github.com/you/repo/raw/master/script'
    echo 'If no URL is given the script is read from stdin.'
    echo
    echo 'output: The output directory the script should be saved to.'
    echo 'By default this is /usr/local/bin on Unix systems, and C:\Users\you\AppData\Local\script on Windows.'
}

NAME=''
OUTPUT=''
URL=''

while [ $# -gt 0 ]
do
    case "$1" in
        '-?'|-h|--help) help; exit 0 ;;
        -n|--name) NAME="$2"; shift ;;
        -o|--output) OUTPUT="$2"; shift ;;
        -u|--url) URL="$2"; shift ;;
        *) help; exit 1 ;;
    esac
    shift
done

script=$(< /dev/stdin)
